# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: "opensafely-core/setup-action@v1"
      with:
        python-version: "3.11"
        cache-dependency-path: "requirements.*.txt"
        install-just: true
    - name: Install dependencies
      run: |
        just devenv
    - name: Test
      run: |
        just test
